routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ReservationController@listAcara')->name('acara');

Route::group(['prefix'=>'admin'],function(){
  Route::get('/login', 'AdminController@showLoginForm')->name('admin.loginForm');
  Route::get('/login', 'AdminController@attemptLogin')->name('admin.login');

Route::group(['middleware'=>'auth:admin'],function(){
  Route::resource('movie', 'MovieController');
  Route::resource('user', 'UserController');
  Route::get('/home', 'HomeController@indexAdmin')->name('home.admin');
});
});
Route::group(['middleware'=>'auth'],function(){
  Route::get('/reservations', 'ReservationController@all')->('reserve.all');
  Route::get('/reservations/{id}', 'ReservationController@index');
  Route::post('/reservation/create', 'ReservationController@create');
  Route::post('/reservation/step2', 'ReservationController@addReservation');


  Route::get('/home', 'HomeController@index')->name('home.user');
});
  Auth::routes();

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="manifest" href="{{  asset('fav/manifest.json') }}">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="{{ asset('fav/ms-icon-144x144.png') }}">
<meta name="theme-color" content="#ffffff">

<link rel="icon" type="image/png" href="{{ asset('logo.png') }}">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    {{-- <script src="{{ asset('js/app.js') }}" ></script> --}}

<style media="screen">
  .btn{
    cursor:pointer;
  }
</style>


   <link rel="stylesheet" href="{{ asset('font-awesome/css/font-awesome.min.css') }}" >
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
   <!-- CSS Files -->
   <link href="{{ asset('kit/css/bootstrap.min.css') }}" rel="stylesheet" />
   <link href="{{ asset('kit/css/light-bootstrap-dashboard.css?v=2.0.1') }}" rel="stylesheet" />


   <!--   Core JS Files   -->
   <script src="{{ asset('kit/js/core/jquery.3.2.1.min.js') }}" type="text/javascript"></script>
   <script src="{{ asset('kit/js/core/popper.min.js') }}" type="text/javascript"></script>
   <script src="{{ asset('kit/js/core/bootstrap.min.js') }}" type="text/javascript"></script>
   <!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
   <script src="{{ asset('kit/js/plugins/bootstrap-switch.js') }}"></script>


   <!-- Control Center for Light Bootstrap Dashboard: scripts for the example pages etc -->
   <script src="{{ asset('kit/js/light-bootstrap-dashboard.js?v=2.0.1') }}" type="text/javascript"></script>

</head>
<style media="screen">
  .navbar-brand{
    color:#ffff !important;
  }
  .nav-link{
      color:#ffff !important;
    }
    .nav-link:hover{
        color:yellow !important;
      }
</style>
<body>
    <div class="wrapper">
      @include('layouts.sidebar')
        <div class="main-panel">
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg " style="background-color: #980000" color-on-scroll="500">
                <div class=" container-fluid  ">

                    <button href="" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navigation">
                        <ul class="nav navbar-nav mr-auto">


                        </ul>
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{{  route('akun.index')}}">
                                    <span class="no-icon">Account</span>
                                </a>
                            </li>


                            <li class="nav-item">
                              <a class="nav-link" href="{{ route('logout') }}"
                                 onclick="event.preventDefault();
                                               document.getElementById('logout-form').submit();">
                                               <i class="fa fa-sign-out no-icon"  style="margin-right: 30px;">Logout</i>


                              </a>

                              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                  @csrf
                              </form>
                            </li>

                        </ul>
                    </div>
                </div>
            </nav>
            <!-- End Navbar -->
            <div class="content">
                <div class="container-fluid">

                  @yield('content')
            {{-- <footer class="footer">
                <div class="container">
                    <nav>
                        <ul class="footer-menu">
                            <li>
                                <a href="#">
                                    Home
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Company
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Portfolio
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Blog
                                </a>
                            </li>
                        </ul>
                        <p class="copyright text-center">
                            ©
                            <script>
                                document.write(new Date().getFullYear())
                            </script>
                            <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
                        </p>
                    </nav>
                </div>
            </footer> --}}
        </div>
    </div>
</div>
</div>
</body>
</html>
@yield('script')

resources/views/layouts/app2.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link rel="apple-touch-icon" sizes="57x57" href="{{  asset('fav/apple-icon-57x57.png') }}">
<link rel="apple-touch-icon" sizes="60x60" href="{{  asset('fav/apple-icon-60x60.png') }}">
<link rel="apple-touch-icon" sizes="72x72" href="{{  asset('fav/apple-icon-72x72.png') }}">
<link rel="apple-touch-icon" sizes="76x76" href="{{  asset('fav/apple-icon-76x76.png') }}">
<link rel="apple-touch-icon" sizes="114x114" href="{{  asset('fav/apple-icon-114x114.png') }}">
<link rel="apple-touch-icon" sizes="120x120" href="{{  asset('fav/apple-icon-120x120.png') }}">
<link rel="apple-touch-icon" sizes="144x144" href="{{  asset('fav/apple-icon-144x144.png') }}">
<link rel="apple-touch-icon" sizes="152x152" href="{{  asset('fav/apple-icon-152x152.png') }}">
<link rel="apple-touch-icon" sizes="180x180" href="{{  asset('fav/apple-icon-180x180.png') }}">
<link rel="icon" type="image/png" sizes="192x192"  href="{{  asset('fav/android-icon-192x192.png') }}">
<link rel="icon" type="image/png" sizes="32x32" href="{{  asset('fav/favicon-32x32.png') }}">
<link rel="icon" type="image/png" sizes="96x96" href="{{  asset('fav/favicon-96x96.png') }}">
<link rel="icon" type="image/png" sizes="16x16" href="{{  asset('fav/favicon-16x16.png') }}">
<link rel="manifest" href="{{  asset('fav/manifest.json') }}">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="{{ asset('fav/ms-icon-144x144.png') }}">
<meta name="theme-color" content="#ffffff">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    {{-- <script src="{{ asset('js/app.js') }}" ></script> --}}
    <script src="{{ asset('js/app.js') }}" ></script>
    <script src="{{ asset('tinymce/tinymce.min.js') }}" ></script>

    <link rel="stylesheet" href="{{ asset('font-awesome/css/font-awesome.min.css') }}" >

    <!-- Fonts -->

    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!--     Fonts and icons     -->
   <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />


</head>
<body>
    <div id="app">

        <nav class="navbar navbar-expand-md bg-info">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                  <img src="{{ asset('logo.png') }}"  style="width: 50px;" alt="">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                      @auth ('web')
                        <li class="nav-item ">
                          <a class="nav-link" href="{{ url('/'.Auth::user()->role()) }}" > Dashboard </a>
                        </li>
                      @endauth

                      @foreach (App\Website::all() as $key => $value)
                        <li class="nav-item ">
                          <a class="nav-link" href="{{ route('prof',$value->slug) }}">{{ $value->nama }}</a>
                        </li>
                      @endforeach
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">


            @yield('content')
        </main>
    </div>
</body>
</html>
@yield('script')

resources/views/layouts/print.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">



    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
           <meta name="viewport"
                 content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
           <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ config('app.name', 'Laravel') }}</title>


    <!-- CSS Files -->
    <link href="{{ asset('kit/css/bootstrap.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('kit/css/light-bootstrap-dashboard.css?v=2.0.1') }}" rel="stylesheet" />


   <link rel="stylesheet" href="{{ asset('font-awesome/css/font-awesome.min.css') }}" >
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
   <!-- CSS Files -->

</head>

<body>

<center>
<b> KEMENTRIAN RISET, TEKNOLOGI, DAN PENDIDIKAN TINGGI</b>
</center>
  <center>
  <b>  Universitas Singaperbangsa Karawang </b>
  </center>
  <center>
<b>    DAFTAR NOMINATIF TUNJANGAN</b>
  </center>
  <center>
<b>    PERIODE TUNJANGAN {{ bulan(Request::get('bulan')) }} {{ Request::get('tahun') }}</b>
  </center>

                  @yield('content')
                  <br>
                  <center>
                  <table  style="text-align:center; margin: 0 auto;">
                    <td><br>

Mengetahui <br>
Rektor
<br><br><br> <br>
H.M. WAHYUDIN ZARKASYI <br>
NIP. 19570807 1986011001

                    </td>
                    <td width="300px">

                    </td>
                    <td>
                      Karawang, {{  date('j').' '.bulan(date('n')).' '.date('Y') }} <br>
an. Kepala Biro Umum dan Keuangan <br>
       Kepala Bagian Umum
       <br><br><br> <br>
TOTO SUHARTO <br>
NIP. 196604181986021002
                    </td>
                  </table>
</center>
</body>
</html>

resources/views/layouts/sidebar.blade.php
<div class="sidebar" data-color="black"  data-image="{{ asset('kit/img/sidebaruns.jpg') }}">
    <!--
Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"

Tip 2: you can also add an image using data-image tag
-->
    <div class="sidebar-wrapper">
        <div class="logo">
            <a href="  {{ url('/') }}" class="simple-text">
                <img src="{{ asset('logo.png') }}"  style="width: 50px;" alt="">
                {{ config('app.name', 'Laravel') }}
            </a>
        </div>
        <ul class="nav">

              @auth('admin')
              <li class="nav-item {{ Request::is('/') ? 'active' : '' }}">
                  <a class="nav-link" href="{{ route('home') }}">
                      <i class="nc-icon nc-chart-pie-35"></i>
                      <p>Dashboard</p>
                  </a>
              </li>
                <li class="nav-item {{ Request::is('movie','movie/*') ? 'active' : '' }}">
                  <a class="nav-link" href="{{ route('movie.index') }}">
                      <i class="nc-icon nc-circle-09"></i>
                      <p>Movies</p>
                  </a>
              </li>
              <li class="nav-item {{ Request::is('user','user/*') ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('user.index').'?bulan='.date('n').'&tahun='.date('Y') }}">
                    <i class="nc-icon nc-circle-09"></i>
                    <p>User</p>
                </a>
            </li>

          @endauth
          @auth ('web')
            @auth('admin')
            <li class="nav-item {{ Request::is('/') ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('home') }}">
                    <i class="nc-icon nc-chart-pie-35"></i>
                    <p>Dashboard</p>
                </a>
            </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ route('acara') }}">
                    <i class="nc-icon nc-circle-09"></i>
                    <p>List Acara</p>
                </a>
            </li>
            <li class="nav-item {{ Request::is('reserve','reserve/*') ? 'active' : '' }}">
              <a class="nav-link" href="{{ route('reserve.all') }}">
                  <i class="nc-icon nc-circle-09"></i>
                  <p>Pesanana</p>
              </a>
          </li>
          @endauth



        </ul>
    </div>
</div>